Feature/sig 3 register user resticctions
sigsa-pf2022/sigsa-frontend pull request #3
Opened 2022-09-05 03:22 UTC by MatiiBr

2022-09-05 14:49 UTC, pedro-mar99 requested changes

2022-09-05 14:49 UTC, pedro-mar99 commented on src/app/views/login/login.page.ts
> +            <app-password-input controlName="password"> </app-password-input>
Falta el placeholder :)

2022-09-05 14:49 UTC, pedro-mar99 commented on src/app/views/login/login.page.ts
> +import {
Revisar import, no se están usando

2022-09-08 23:49 UTC, MatiiBr commented on src/app/views/login/login.page.ts
> +            <app-password-input controlName="password"> </app-password-input>
Ready

2022-09-08 23:49 UTC, MatiiBr commented on src/app/views/login/login.page.ts
> +import {
Ready

2022-09-12 14:50 UTC, pedro-mar99 approved these changes

2022-09-12 14:51 UTC, merged